version: '3.9'

x-base_service: &base_service
    ports:
      - "7860:7860"
    volumes:
      - &v1 ./data:/data
      - &v2 ./output:/output
      - &vf1 models:/data/StableDiffusion
    stop_signal: SIGINT
    deploy:
      resources:
        reservations:
          devices:
              - driver: nvidia
                device_ids: ['0']
                capabilities: [gpu]

name: webui-docker

services:
  download:
    build: ./services/download/
    profiles: ["download"]
    volumes:
      - *v1
      - *vf1

  auto: &automatic
    <<: *base_service
    profiles: ["auto"]
    build: ./services/AUTOMATIC1111
    image: sd-auto:51
    environment:
      - CLI_ARGS=--allow-code --medvram --xformers --enable-insecure-extension-access --api
    volumes:
      - packages:/usr/local/lib/python3.10/site-packages

  auto-cpu:
    <<: *automatic
    profiles: ["auto-cpu"]
    deploy: {}
    environment:
      - CLI_ARGS=--no-half --precision full --allow-code --enable-insecure-extension-access --api

  invoke:
    <<: *base_service
    profiles: ["invoke"]
    build: ./services/invoke/
    image: sd-invoke:27
    environment:
      - PRELOAD=true
      - CLI_ARGS=--no-nsfw_checker --no-safety_checker --xformers

  sygil: &sygil
    <<: *base_service
    profiles: ["sygil"]
    build: ./services/sygil/
    image: sd-sygil:16
    environment:
      - CLI_ARGS=--optimized-turbo
      - USE_STREAMLIT=0

  sygil-sl:
    <<: *sygil
    profiles: ["sygil-sl"]
    environment:
      - USE_STREAMLIT=1

  comfy: &comfy
    <<: *base_service
    profiles: ["comfy"]
    build: ./services/comfy/
    image: sd-comfy:1
    tty: true
    environment:
      - CLI_ARGS=


  comfy-cpu:
    <<: *comfy
    profiles: ["comfy-cpu"]
    deploy: {}
    environment:
      - CLI_ARGS=--cpu

  copy-checkpoint:
    image: busybox
    command: cp -R /data/StableDiffusion/ /checkpoints
    volumes:
      - *v1
      - models:/checkpoints

volumes:
  models:
  packages:
