[general]
shuffle_caption = true
caption_extension = '.txt'
keep_tokens = 1

[[datasets]]
resolution = 512

  [[datasets.subsets]]
  image_dir = '/data/training-shs'
  class_tokens = 'shs'

  [[datasets.subsets]]
  image_dir = '/data/training-cco'
  class_tokens = 'cco'

